// Canonical suit-isomorphic flop enumeration (full-density cost plan WS2).
//
// There are C(52,3) = 22,100 raw flops; under suit relabeling they collapse to
// exactly 1,755 equivalence classes (1,430 unpaired-distinct-rank × 5 suit
// patterns + 312 paired × 2 + 13 trips). The solve grid's full-density mode
// (`TLSOLVE_FLOPS=all1755`) solves one representative per class — solving two
// isomorphic flops would be paying twice for the same GTO solution.
//
// Canonicalization: for each raw flop, take the lexicographically-smallest
// serialization over all 24 suit permutations (cards sorted rank-desc,
// suit-asc within rank). Brute force over 22,100 × 24 is instant and immune to
// the classic within-rank-ordering pitfalls of first-appearance relabeling.
//
// The canonicalization itself lives in the app (lib/explorer/board_iso.dart —
// pure, web-safe) so the Study explorer's suit normalizer and this grid
// tooling share ONE implementation (the pack_codec pattern); re-exported here
// so tool/test callers keep their import. Byte-identity with the committed
// slice files is test-locked (test/solver/flop_enum_test.dart +
// test/explorer/board_iso_test.dart).

import 'dart:io';

import 'package:tablelab/explorer/board_iso.dart';

export 'package:tablelab/explorer/board_iso.dart'
    show allIsoFlops, canonicalFlop;

/// A stride-sampled slice of [all]: [count] entries at phase [offset] — for
/// ARBITRARY-COUNT calibration sampling (e.g. a 200-flop timing slice).
/// Stride sampling (every ~Nth of the sorted list) spans the rank/suit space
/// evenly — the sorted list starts at "2c 2d 2h", so a prefix slice would skew
/// toward low disconnected boards and bias any timing calibration.
///
/// For PARTITIONS use [modSlice] — it is the partition primitive and handles
/// any way-count. (When [count] divides `all.length`, the two coincide:
/// `strideSlice(all, len ~/ m, k)` == `modSlice(all, k, m)` index-for-index —
/// the committed 5-way slice351 files are equivalently `mod 5 k` outputs.)
List<String> strideSlice(List<String> all, int count, int offset) {
  final out = <String>[];
  for (var i = 0; i < count; i++) {
    final idx = (offset + (i * all.length) ~/ count) % all.length;
    out.add(all[idx]);
  }
  return out;
}

/// The PARTITION primitive: a round-robin "deal" slice of [all] — every m-th
/// entry starting at [k] (indices k, k+m, k+2m, …). Partitions exactly for ANY
/// m: slices differ in size by at most one when m doesn't divide the list
/// (1,755 mod 4 → sizes 439/439/439/438). Same texture-balancing property as
/// [strideSlice] (the sorted list is dealt around the table). The bulk
/// campaign's 4-box fleet uses m=4 (see the partition test in
/// test/solver/flop_enum_test.dart). Throws on invalid [k]/[m] — an m of 0
/// would otherwise loop forever, and a non-canonical residue (k ≥ m) would
/// silently produce a non-partition slice.
List<String> modSlice(List<String> all, int k, int m) {
  if (m < 1 || k < 0 || k >= m) {
    throw ArgumentError('modSlice needs m >= 1 and 0 <= k < m (got k=$k m=$m)');
  }
  return [for (var i = k; i < all.length; i += m) all[i]];
}

void _writeSlice(String path, List<String> flops, String desc) {
  File(path).writeAsStringSync(
      '# ${flops.length} $desc — generated by flop_enum.dart\n'
      '${flops.join('\n')}\n');
  stdout.writeln('wrote ${flops.length} flops to $path');
}

/// CLI: emit a slice of the 1,755 canonical flops as a TLSOLVE_FLOPS=file:
/// input — for calibration slices and for splitting a full-density bulk run
/// across boxes (commit the slice files so the launcher's `git archive` ships
/// them to the box).
///   `dart run tool/solver/flop_enum.dart <count> <outPath> [offset]`  (stride)
///   `dart run tool/solver/flop_enum.dart mod <m> <k> <outPath>`       (deal)
Never _usage() {
  stderr.writeln('usage: flop_enum <count> <outPath> [offset]   (stride sample)\n'
      '       flop_enum mod <m> <k> <outPath>          (partition deal)');
  exit(64);
}

int _intArg(String s) => int.tryParse(s) ?? _usage();

void main(List<String> args) {
  if (args.isNotEmpty && args[0] == 'mod') {
    if (args.length < 4) _usage();
    final m = _intArg(args[1]);
    final k = _intArg(args[2]);
    if (m < 1 || k < 0 || k >= m) {
      stderr.writeln('need m >= 1 and 0 <= k < m');
      exit(64);
    }
    _writeSlice(args[3], modSlice(allIsoFlops(), k, m),
        'mod-$m dealt canonical flops (k=$k)');
    return;
  }
  if (args.length < 2) _usage();
  final count = _intArg(args[0]);
  final offset = args.length > 2 ? _intArg(args[2]) : 0;
  _writeSlice(args[1], strideSlice(allIsoFlops(), count, offset),
      'stride-sampled canonical flops (offset $offset)');
}
